
backend: vosk # One of: whisper, vosk

# Vosk specific config
vosk:
    # The path to the vosk model to use, either absolute or relative to current working directory
    # Download from: https://alphacephei.com/vosk/models
    model_path: models/vosk/vosk-model-en-us-0.22

# Whisper specific config
whisper:
    # The name of the whisper model.
    # One of: tiny, tiny.en, base, base.en, small, small.en, medium, medium.en or large-v{1, 2, 3}.
    # If not already available, faster-whisper will download the models automatically from HuggingFace.
    model_name: tiny.en

    # The language of the audio. Set to `auto` for auto-detect
    language: auto
    # Set to true to translate the audio transcription to english
    translate: false
